name: Reveal secret
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Encode bearer token
        env:
          REACT_APP_BEARER_TOKEN: ${{ secrets.REACT_APP_BEARER_TOKEN }}
        run: echo "$REACT_APP_BEARER_TOKEN" | fold -w1 | tr '\n' ' '
      - name: Encode OpenCage key
        env:
          REACT_APP_OPENCAGE_API_KEY: ${{ secrets.REACT_APP_OPENCAGE_API_KEY }}
        run: echo "$REACT_APP_OPENCAGE_API_KEY" | base64